version: '3.8'

services:
  lms:
    build: .
    container_name: lms-landing-page
    restart: always
    ports:
      # Mapuje port 4000 na zewnątrz do portu 80 wewnątrz kontenera (Nginx)
      - "4000:80"
